### ISSUE TITLE
netperfrunner.sh & betterspeedtest.sh

### ISSUE THREAD

**Issue by negan07** [richb-hanover/OpenWrtScripts#1]
Made some topic scripts small adaptations for embedded system with very tiny set of shell commands.

[scripts.zip](https://github.com/richb-hanover/OpenWrtScripts/files/1969028/scripts.zip)

In detail: 

- [x] tuned usage commentary
- [x] removed `ping` dots & `trap wait`
- [x] replaced `mktemp` with `touch ${FILE}`.`date "+%Y-%m-%d_%H:%M:%S"` suffix
- [x] replaced `pgrep -p netperf $$` with `pidof netperf`
- [x] on summarize_pings(): replaced `sort` with `awk` bubble-sort
- [x] replaced `for/seq` with `while/let` loops
- [x] converted output values to Kbps
- [x] redirected `echo`'s error messages to stderr
- [x] some more compact code size

if helpful

**Comment by negan07** [comment]
made a further improvement:

[network-test.zip](https://github.com/richb-hanover/OpenWrtScripts/files/1972207/network-test.zip)

This script is the union of `betterspeedtest.sh` and `netperfrunner.sh` and it is invoked with a symlink named as each one. If no symlink is given, `betterspeedtest.sh` is run as default.

swapped ping killings with output results, created specific functions for both scripts and repeated actions: `start_ping(), kill_pings(), netperf_loop(), netperf_wait(), create_tmp_files()`

if helpful

**Comment by richb-hanover** [comment]
Hi @negan07 - Thanks for this update. It's interesting how parallel development goes on...

Over on OpenWrt, guidosarducci has created an OpenWrt package that can be installed and then used for exactly these kinds of tests. https://forum.openwrt.org/t/speedtest-new-package-to-measure-network-performance/24647

I can't say whether this would work in the kinds of memory-constrained environments where you designed your scripts.

Best regards, and thanks!
